# Generated by Django 5.1.3 on 2024-11-12 12:27

import imagesense.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesense', '0005_user_user_permissions_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=imagesense.models.get_timestamped_filename),
        ),
    ]
