# Generated by Django 5.1.3 on 2024-11-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesense', '0012_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='relationship',
            field=models.CharField(blank=True, help_text='Relationship to the user', max_length=50, null=True),
        ),
    ]
