# Generated by Django 5.1.3 on 2024-11-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesense', '0016_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, help_text='Add your message', null=True),
        ),
    ]
