# Generated by Django 5.1.3 on 2024-11-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesense', '0017_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=1, error_messages={'blank': 'Please enter a comment before submitting.', 'null': 'Comment cannot be null. It is a required field.'}, help_text='Add your message'),
            preserve_default=False,
        ),
    ]
