# Generated by Django 5.1.3 on 2024-11-18 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='group_thumbnails/')),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allow_member_uploads', models.BooleanField(default=False, help_text='Allow regular members to upload photos')),
                ('allow_admin_uploads', models.BooleanField(default=True, help_text='Allow admin members to upload photos')),
                ('can_upload_photos', models.ManyToManyField(blank=True, help_text='Users who can upload photos to this group', related_name='uploadable_groups', to=settings.AUTH_USER_MODEL)),
                ('can_view_group', models.ManyToManyField(blank=True, help_text='Users who can view this group', related_name='viewable_groups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
