# Generated by Django 5.1.3 on 2024-11-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_customgroup_access_alter_groupmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
