# Generated by Django 5.1.3 on 2024-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupmember_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='access',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Public', 'Public')], max_length=50, null=True),
        ),
    ]
