# Generated by Django 5.1.3 on 2024-11-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_customgroup_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='access',
            field=models.CharField(blank=True, choices=[('1', 'Private'), ('2', 'Public')], max_length=50, null=True),
        ),
    ]
